### ISSUE TITLE
Why setting width to 100% ?

### ISSUE THREAD

**Issue by ghost** [hunzaboy/bulma-megamenu#1]
Hi,

first of all thanks for this extension.

One question: why setting the width to 100% and not letting it to auto adjust to the content ?

Regards

**Comment by hunzaboy** [comment]
@Wikiki, just in case someone have changed the width in their stylesheet for the navbar-dropdown.  Seemed like it was not needed.

**Comment by hunzaboy** [comment]
Removed the width property from the dropdown.
