### ISSUE TITLE
Menu not covering the whole screen width

### ISSUE THREAD

**Issue by nedpals** [hunzaboy/bulma-megamenu#4]
Hi! I was just wondering if you have any plans to update or have any workarounds for this? The mega-menu does not seem to cover the entire screen width anymore far from what I expected in the demo. Great extension by the way!

I'm using the latest version (0.7.1).

# Expected
From the [demo](https://codepen.io/hunzaboy/pen/yoPKQW).

# Actual Output
![screenshot from 2018-05-07 19-40-08](https://user-images.githubusercontent.com/7358345/39700095-85b2f77e-522e-11e8-917a-235367e6483f.png)

***Note: I intentionally colored the background for clarity in this screencap***

**Comment by hunzaboy** [comment]
Is this still a problem? sorry for the late reply, was busy with work.

**Comment by 01ssela** [comment]
is because of .container
