### ISSUE TITLE
Does it suppose to work with current version of Bulma 0.7.5?

### ISSUE THREAD

**Issue by mark-stopka** [hunzaboy/bulma-megamenu#8]
Hi, I am trying to implement your plug-in into a WordPress theme, but I am relatively new to Bulma, my current theme is at [our website](https://www.perlur.cloud/), and even when I made the README modifications using Chrome development tools, I was not able to get the megamenu to work...

Are there some upgrades needed for the plug-in to support newest release? I see that the last commit in the .scss file is two years old, so I was wondering if something on a Bulma side has not changed...

**Comment by hunzaboy** [comment]
Yes it still works with it. :)
